Repository Step3-kakao-tech-campus/Team14_BE, pull requests merged in 2023-10, with the labels that each got.

#17 feat: 로그인 , 회원가입, 토큰 검증 및 발급 구현
  build.gradle
  src/main/java/com/kakaotech/team14backend/auth/AuthenticationSuccessHandler.java
  src/main/java/com/kakaotech/team14backend/auth/PrincipalDetails.java
  src/main/java/com/kakaotech/team14backend/config/SecurityConfig.java
  src/main/java/com/kakaotech/team14backend/inner/member/model/Member.java
  src/main/java/com/kakaotech/team14backend/inner/member/model/Role.java
  src/main/java/com/kakaotech/team14backend/inner/member/model/Status.java
  src/main/java/com/kakaotech/team14backend/inner/member/repository/MemberRepository.java
  src/main/java/com/kakaotech/team14backend/jwt/JwtAuthenticationFilter.java
  src/main/java/com/kakaotech/team14backend/jwt/JwtProvider.java
  src/main/java/com/kakaotech/team14backend/outer/login/controller/LoginController.java
  src/main/java/com/kakaotech/team14backend/outer/login/dto/TokenDTO.java
  src/main/java/com/kakaotech/team14backend/outer/login/service/PrincipalOauth2UserService.java
  src/main/resources/application.properties
  src/test/java/com/kakaotech/team14backend/inner/post/usecase/FindPopularPostUsecaseTest.java
  src/test/java/com/kakaotech/team14backend/inner/post/usecase/SchedulePostViewCountUsecaseTest.java
Labels: Priority: Medium

#84 My Page 유저가 올린 게시물들 조회하는 기능 구현 with PairProgramming
  src/main/java/com/kakaotech/team14backend/inner/post/repository/PostRepository.java
  src/main/java/com/kakaotech/team14backend/inner/post/usecase/FindPersonalPostListUsecase.java
  src/main/java/com/kakaotech/team14backend/outer/post/controller/PostController.java
  src/main/java/com/kakaotech/team14backend/outer/post/dto/GetPersonalPostListResponseDTO.java
  src/main/java/com/kakaotech/team14backend/outer/post/dto/GetPersonalPostResponseDTO.java
  src/main/java/com/kakaotech/team14backend/outer/post/mapper/PostMapper.java
  src/main/java/com/kakaotech/team14backend/outer/post/service/PostService.java
  src/test/java/com/kakaotech/team14backend/outer/controller/PostControllerTest.java
Labels: Priority: Medium, Type : Feature

#141 인기 게시물 스케줄링값 설정 이슈 해결
  src/main/java/com/kakaotech/team14backend/outer/post/schedule/SchedulePopularPost.java
  src/main/resources/application-lab.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: Priority: High
